name: Continuous Integration

on:
  push:
    branches:
      - main
      - vc-ssi-integration-tests
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18

      - name: Report known vulnerabilities
        run: npm audit

  test-with-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build all workspace packages
        run: npm run build

      - name: Run linter for all packages
        run: npm run lint --ws

      - name: start services tests need (dwn node, ssi service)
        run: cd testfiles && docker-compose up -d

      - name: wait for services to be ready
        run: until curl -sf http://localhost:3000/health; do sleep .1; done && until curl -sf http://localhost:8080/health; do sleep .1; done

      - name: Run tests for all packages
        run: npm run test:node --ws -- -i -f ssi --color
        env:
          DWN_URL: http://localhost:3000

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        # this test is currently expected to fail
      - name: Run web5 SSI integration tests
        run: cd packages/web5 && npm run test:node --ws -- -f ssi --color
        env:
          SSI_BASE_URL: http://localhost:8080
          LOG_SSI_REQUESTS: 'true'

  test-with-browsers:
    # Run browser tests using macOS so that WebKit tests don't fail under a Linux environment
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build all workspace packages
        run: npm run build

      - name: Run tests for all packages
        run: npm run test:browser --ws -- -i -f ssi --color
